/*
  21503877 Darnala Baptiste
  20140442 Eliott Duverger
*/


DROP TABLE IF EXISTS FAIT_TRAJET;
DROP TABLE IF EXISTS TRAJET;
DROP TABLE IF EXISTS AVIS;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS ERREUR;

CREATE TABLE UTILISATEUR(
  ID_UTILISATEUR INTEGER(10) AUTO_INCREMENT primary key,
  NOM VARCHAR(20) NOT NULL,
  PRENOM VARCHAR(20) NOT NULL,
  AGE INTEGER(2) NOT NULL,
  SEXE VARCHAR(6) CHECK (SEXE IN ('HOMME', 'FEMME')),
  MAIL VARCHAR(50) NOT NULL,
  MDP VARCHAR(30) NOT NULL,
  ETAT BOOLEAN,
  NOTE INTEGER(2) CHECK (NOTE >= 0 AND NOTE <= 5)
);

CREATE TABLE AVIS(
  ID_CONDUCTEUR INTEGER(10),
  ID_PASSAGER INTEGER(10),
  NOTE INTEGER(2) CHECK (NOTE >= 0 AND NOTE <= 5),
  COMMENTAIRE TEXT,
  CONSTRAINT FK_CONDUCTEUR foreign key(ID_CONDUCTEUR) references UTILISATEUR(ID_UTILISATEUR),
  CONSTRAINT FK_PASSAGER_AVIS foreign key(ID_PASSAGER) references UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE TRAJET(
  ID_TRAJET INTEGER(10) AUTO_INCREMENT primary key,
  TYPE BOOLEAN,
  VILLE_DEP VARCHAR(20) NOT NULL,
  ADRESSE_DEPART VARCHAR(100),
  VILLE_ARR VARCHAR(20) NOT NULL,
  ADRESSE_ARR VARCHAR(100),
  DISTANCE INT(10),
  PRIX FLOAT(5,2) CHECK (PRIX > 0),
  DATE_DEP DATE,
  DISPONIBLE BOOLEAN,
  ID_CONDUCTEUR INTEGER(10),
  NB_PLACE INTEGER(2) CHECK (NB_PLACE> 0),
  CONSTRAINT FK_CONDUCTEUR foreign key(ID_CONDUCTEUR) references UTILISATEUR(ID_CONDUCTEUR)
);

CREATE TABLE FAIT_TRAJET(
  ID_TRAJET INTEGER(10),
  ID_PASSAGER INTEGER(10),
  CONSTRAINT FK_TRAJET foreign key(ID_TRAJET) references TRAJET(ID_TRAJET),
  CONSTRAINT FK_PASSAGER foreign key(ID_PASSAGER) references UTILISATEUR(ID_UTILISATEUR)
);
