DROP TABLE IF EXISTS FAIT_TRAJET;
DROP TABLE IF EXISTS TRAJET;
DROP TABLE IF EXISTS AVIS;
DROP TABLE IF EXISTS VOITURE;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS ERREUR;

CREATE TABLE UTILISATEUR(
  ID_UTILISATEUR INTEGER(10) AUTO_INCREMENT primary key,
  NOM VARCHAR(20) NOT NULL,
  PRENOM VARCHAR(20) NOT NULL,
  AGE INTEGER(2) NOT NULL,
  SEXE VARCHAR(6) CHECK (SEXE IN ('HOMME', 'FEMME')),
  MAIL VARCHAR(50) NOT NULL,
  MDP VARCHAR(30) NOT NULL,
  ETAT BOOLEAN,
  NOTE INTEGER(2) CHECK (NOTE >= 0 AND NOTE <= 5)
);

CREATE TABLE VOITURE(
  ID_VOITURE INTEGER(10) AUTO_INCREMENT primary key,
  NB_PLACES INTEGER(2),
  ID_PROPRIETAIRE INTEGER(10),
  CONSTRAINT FK_PROP_VOI foreign key(ID_PROPRIETAIRE) references UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE AVIS(
  ID_CONDUCTEUR INTEGER(10),
  ID_PASSAGER INTEGER(10),
  NOTES INTEGER(10),
  COMMENTAIRE TEXT,
  CONSTRAINT FK_CONDUCTEUR foreign key(ID_CONDUCTEUR) references UTILISATEUR(ID_UTILISATEUR),
  CONSTRAINT FK_PASSAGER_AVIS foreign key(ID_PASSAGER) references UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE TRAJET(
  ID_TRAJET INTEGER(10) AUTO_INCREMENT primary key,
  TYPE BOOLEAN,
  VILLE_DEP VARCHAR(20),
  ADRESSE_DEPART VARCHAR(100),
  VILLE_ARR VARCHAR(20),
  ADRESSE_ARR VARCHAR(100),
  DISTANCE INT(10),
  PRIX FLOAT(5,2),
  DATE_DEP DATE,
  DISPONIBLE BOOLEAN,
  ID_VOITURE INTEGER(10),
  ID_CONDUCTEUR INTEGER(10),
  NB_PLACE INTEGER(2),
  CONSTRAINT FK_VOITURE foreign key(ID_VOITURE) references VOITURE(ID_VOITURE),
  CONSTRAINT FK_CONDUCTEUR foreign key(ID_CONDUCTEUR) references UTILISATEUR(ID_CONDUCTEUR)
);

CREATE TABLE FAIT_TRAJET(
  ID_TRAJET INTEGER(10),
  ID_PASSAGER INTEGER(10),
  CONSTRAINT FK_TRAJET foreign key(ID_TRAJET) references TRAJET(ID_TRAJET),
  CONSTRAINT FK_PASSAGER foreign key(ID_PASSAGER) references UTILISATEUR(ID_UTILISATEUR)
);

-- Création de la table Erreur
CREATE TABLE Erreur (
    id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    erreur VARCHAR(255) UNIQUE);

-- Insertion de l'erreur qui nous intéresse
INSERT INTO Erreur (erreur) VALUES ('Erreur : Le prix est trop élevée');
