DROP PROCEDURE IF EXISTS moyenne;
DROP TRIGGER IF EXISTS prix_abuse;
DROP TRIGGER IF EXISTS traj_complet;



DELIMITER |
CREATE PROCEDURE moyenne (uti_id INT, OUT notes INT)
BEGIN
    SELECT AVG(NOTES) INTO @notes
    FROM UTILISATEUR, AVIS
    WHERE AVIS.ID_CONDUCTEUR = UTILISATEUR.ID_UTILISATEUR
    AND uti_id = AVIS.ID_CONDUCTEUR;
END |
DELIMITER ;



DELIMITER |
CREATE TRIGGER prix_abuse BEFORE INSERT
ON TRAJET FOR EACH ROW
BEGIN
    IF NEW.PRIX > (NEW.DISTANCE * 0.1)
      THEN
        SET NEW.PRIX = NEW.DISTANCE*0.1;
    END IF;
END |
DELIMITER ;


DELIMITER |
CREATE TRIGGER traj_complet BEFORE UPDATE
ON TRAJET FOR EACH ROW
BEGIN
    IF NEW.NB_PLACE = 0
      THEN
        SET NEW.DISPONIBLE = FALSE;
    END IF;
END |
DELIMITER ;
