DROP PROCEDURE moyenne;
DROP PROCEDURE nb_traj_dispo;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `moyenne`(IN ID_UTIL INT)
BEGIN
SELECT AVG(NOTES) as MOY
  FROM AVIS, UTILISATEUR
  WHERE ID_CONDUCTEUR = ID_UTIL;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `nb_traj_dispo`(OUT nb_traj INT)
BEGIN
    SELECT COUNT(*) INTO nb_traj
    FROM TRAJET
    WHERE DISPONIBLE = TRUE
    AND DATE_DEP > NOW();
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` TRIGGER `prix_abuse` BEFORE INSERT ON `trajet`
 FOR EACH ROW BEGIN
    IF NEW.PRIX > (NEW.DISTANCE * 0.1)
      THEN
        SET NEW.PRIX = NEW.DISTANCE*0.1;
    END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` TRIGGER `raj_complet` BEFORE UPDATE ON `trajet`
 FOR EACH ROW BEGIN

    IF NEW.NB_PLACE = 0
      THEN
        SET NEW.DISPONIBLE = FALSE;
    END IF;
END$$
DELIMITER ;
